import { BaseSeeder } from '@adonisjs/lucid/seeders'
import FotoProdukLelang from '#models/foto_produk_lelang'
import Lelang from '#models/lelang'
import fs from 'node:fs'
import path from 'node:path'
import { cwd } from 'node:process'

export default class FotoProdukLelangSeeder extends BaseSeeder {
  async run() {
    console.log('📸 Seeding FotoProdukLelang...')

    // Pastikan folder uploads/lelang ada
    const uploadsPath = path.join(cwd(), 'public/uploads/lelang')
    if (!fs.existsSync(uploadsPath)) {
      fs.mkdirSync(uploadsPath, { recursive: true })
      console.log('📁 Created uploads/lelang directory')
    }

    // Get existing lelang IDs
    const lelangs = await Lelang.all()
    if (lelangs.length === 0) {
      console.log('❌ No auctions found. Skipping FotoProdukLelang seeding.')
      return
    }

    // Sample image filenames based on product types
    const sampleImages = [
      'kopi_arabika_1.jpg',
      'kopi_arabika_2.jpg',
      'kopi_robusta_1.jpg',
      'kopi_robusta_2.jpg',
      'beras_premium_1.jpg',
      'beras_premium_2.jpg',
      'beras_organik_1.jpg',
      'beras_organik_2.jpg',
      'default_product_1.jpg',
      'default_product_2.jpg'
    ]

    // Create placeholder images if they don't exist
    console.log('🖼️ Creating placeholder images...')
    sampleImages.forEach(imageName => {
      const imagePath = path.join(uploadsPath, imageName)
      if (!fs.existsSync(imagePath)) {
        // Create a simple text file as placeholder
        const placeholderContent = `Placeholder image for ${imageName}\nGenerated by seeder at ${new Date().toISOString()}`
        fs.writeFileSync(imagePath, placeholderContent)
      }
    })

    // Get product data to determine which images to use
    const lelangsWithProduk = await Lelang.query().preload('produk', (produkQuery) => {
      produkQuery.preload('jenisProduk')
    })

    const fotoProdukData: Array<{
      lelangId: number
      foto: string
      keterangan: string
    }> = []

    // For each lelang, create 2-3 photos
    for (const lelang of lelangsWithProduk) {
      let images: string[] = []

      // Determine images based on product name/type
      const produkName = lelang.produk.namaProduk.toLowerCase()
      const jenisProdukName = lelang.produk.jenisProduk.nama_jenis_produk?.toLowerCase() || ''

      if (produkName.includes('arabika') || jenisProdukName.includes('kopi')) {
        if (produkName.includes('arabika')) {
          images = ['kopi_arabika_1.jpg', 'kopi_arabika_2.jpg']
        } else if (produkName.includes('robusta')) {
          images = ['kopi_robusta_1.jpg', 'kopi_robusta_2.jpg']
        } else {
          images = ['kopi_arabika_1.jpg', 'kopi_arabika_2.jpg'] // default for coffee
        }
      } else if (produkName.includes('beras') || jenisProdukName.includes('beras')) {
        if (produkName.includes('premium')) {
          images = ['beras_premium_1.jpg', 'beras_premium_2.jpg']
        } else if (produkName.includes('organik')) {
          images = ['beras_organik_1.jpg', 'beras_organik_2.jpg']
        } else {
          images = ['beras_premium_1.jpg', 'beras_premium_2.jpg'] // default for rice
        }
      } else {
        // Default images for other products
        images = ['default_product_1.jpg', 'default_product_2.jpg']
      }

      // Create photo entries
      images.forEach((image, index) => {
        fotoProdukData.push({
          lelangId: lelang.id,
          foto: `uploads/lelang/${image}`,
          keterangan: `Foto ${index + 1} untuk ${lelang.produk.namaProduk}${index === 0 ? ' (Utama)' : ''}`
        })
      })
    }

    // Insert all photos in batch
    if (fotoProdukData.length > 0) {
      await FotoProdukLelang.createMany(fotoProdukData)
      console.log(`✅ Created ${fotoProdukData.length} FotoProdukLelang records`)

      // Log summary by lelang
      const groupedByLelang = fotoProdukData.reduce((acc, foto) => {
        acc[foto.lelangId] = (acc[foto.lelangId] || 0) + 1
        return acc
      }, {} as Record<number, number>)

      console.log('📊 Photos created by lelang:')
      Object.entries(groupedByLelang).forEach(([lelangId, count]) => {
        console.log(`   Lelang ID ${lelangId}: ${count} photos`)
      })
    } else {
      console.log('❌ No photo data to insert')
    }
  }
}
